version: "3"

services:
  server:
    container_name: "caomei-auth"
    image: ${DOCKER_IMAGE:-caomeiyouren/caomei-auth}
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      TZ: "Asia/Shanghai"
      # Better Auth 的基础 URL
      NUXT_PUBLIC_AUTH_BASE_URL: "http://localhost:3000"

      # 用于加密、签名和哈希的密钥。
      # 在生产环境中，如果未设置，将抛出错误。
      AUTH_SECRET: ""
      # Redis 配置
      REDIS_URL: "redis://localhost:6379"
      # 数据库配置
      DATABASE_TYPE: sqlite
      # SQLite数据库路径 (仅SQLite使用)
      DATABASE_PATH: database/caomei-auth.sqlite
      # 数据库连接URL (MySQL和PostgreSQL使用)
      # DATABASE_URL: mysql://user:password@localhost:3306/caomei_auth
      # DATABASE_URL: postgresql://user:password@localhost:5432/caomei_auth
      # 数据库表前缀
      DATABASE_ENTITY_PREFIX: caomei_auth_

    volumes:
      - ./logs:/app/logs
      - ./database:/app/database
